AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  auto-fastlane-spaceauth

  Sample SAM Template for auto-fastlane-spaceauth

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 3
    Tracing: Active
  Api:
    TracingEnabled: True

Resources:
  AutoFastlaneSpaceauthFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: auto-fastlane-spaceauth/
      Handler: app.lambda_handler
      Runtime: ruby2.7
      Architectures:
        - arm64
      Events:
        SNSEvent:
          Type: SNS
          Properties:
            Topic: arn:aws:sns:eu-west-1:501431420968:APPLE_2FA_SMS_CODES
