AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  auto-fastlane-spaceauth

  Sample SAM Template for auto-fastlane-spaceauth

Parameters:
  FastlanePassword:
    Type: String
    Description: Apple ID password for Fastlane
    NoEcho: true

Resources:
  SqsQueueForApple2FaSms:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: SqsQueueForApple2FaSms
      DelaySeconds: 0
      MessageRetentionPeriod: 120
      ReceiveMessageWaitTimeSeconds: 0
      VisibilityTimeout: 0
      SqsManagedSseEnabled: true
  SnsSubscription:
    Type: AWS::SNS::Subscription
    Properties:
      Protocol: sqs
      Endpoint: !GetAtt SqsQueueForApple2FaSms.Arn
      Region: "eu-west-1"
      TopicArn: "arn:aws:sns:eu-west-1:501431420968:APPLE_2FA_SMS_CODES"
  AutoFastlaneSpaceauthFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: auto-fastlane-spaceauth/
      Handler: app.lambda_handler
      Runtime: ruby2.7
      Timeout: 150
      Architectures:
        # - arm64 # TODO Uncomment this line to enable ARM64 support (slower to build with Docker)
        - x86_64
      Environment:
        Variables:
          SQS_QUEUE_URL: !Ref SqsQueueForApple2FaSms
          SPACESHIP_2FA_SMS_DEFAULT_PHONE_NUMBER: "+1 (787) 493-0633"
          FASTLANE_USER: "dev-ios@bfansports.com"
          FASTLANE_PASSWORD: !Ref FastlanePassword
          SECRETS_MANAGER_SECRET_ID: "arn:aws:secretsmanager:eu-west-1:501431420968:secret:IOSEnvironment"
      Events:
        FastlaneSpaceauthSchedule:
          Type: Schedule
          Properties:
            Schedule: rate(15 minutes)
            Name: FastlaneSpaceauthSchedule
            Description: Triggers the AutoFastlaneSpaceauthFunction lambda every 15 minutes