AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  auto-fastlane-spaceauth

  Sample SAM Template for auto-fastlane-spaceauth

Resources:
  AutoFastlaneSpaceauthFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: auto-fastlane-spaceauth/
      Handler: app.lambda_handler
      Runtime: ruby2.7
      Architectures:
        - arm64
      Events:
        FastlaneSpaceauthSchedule:
          Type: Schedule
          Properties:
            Schedule: rate(15 minutes)
            Name: FastlaneSpaceauthSchedule
            Description: Triggers the AutoFastlaneSpaceauthFunction lambda every 15 minutes